// Sample data for testing and seeding the database

export const sampleMemories = [
  {
    title: 'Summer Beach Trip',
    description: 'Amazing day at the beach with friends',
    category: 'Travel',
    date: '2024-07-15',
    location: 'Miami Beach, FL',
    story: 'We spent the entire day building sandcastles, playing volleyball, and watching the sunset. It was the perfect summer day!',
    notes: 'Don\'t forget sunscreen next time',
    tags: ['beach', 'summer', 'friends', 'vacation'],
    mood: 'Happy',
    source: 'Personal',
    highlights: 'Sunset photos, beach volleyball championship',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    likes: 45,
  },
  {
    title: 'Birthday Celebration',
    description: 'Surprise birthday party for Sarah',
    category: 'Celebration',
    date: '2024-06-20',
    location: 'New York, NY',
    story: 'We threw an amazing surprise party for Sarah\'s 25th birthday. The look on her face was priceless!',
    notes: 'Best party ever',
    tags: ['birthday', 'party', 'surprise', 'celebration'],
    mood: 'Excited',
    source: 'Personal',
    highlights: 'Surprise reveal, birthday cake, group photos',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=800&h=600&fit=crop',
    likes: 32,
  },
  {
    title: 'Hiking Adventure',
    description: 'Mountain hiking with the team',
    category: 'Adventure',
    date: '2024-05-10',
    location: 'Yosemite National Park, CA',
    story: 'Challenging but rewarding hike to the summit. The view from the top was absolutely breathtaking!',
    notes: 'Bring more water next time',
    tags: ['hiking', 'nature', 'adventure', 'outdoors'],
    mood: 'Accomplished',
    source: 'Personal',
    highlights: 'Summit view, wildlife sightings, team photo',
    image_url: 'https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&h=600&fit=crop',
    likes: 67,
  },
  {
    title: 'Family Reunion',
    description: 'Annual family gathering',
    category: 'Family',
    date: '2024-08-01',
    location: 'Chicago, IL',
    story: 'Three generations came together for our annual family reunion. So much love and laughter!',
    notes: 'Plan for next year',
    tags: ['family', 'reunion', 'tradition', 'love'],
    mood: 'Grateful',
    source: 'Personal',
    highlights: 'Family photos, traditional recipes, games',
    image_url: 'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=800&h=600&fit=crop',
    likes: 89,
  },
  {
    title: 'Graduation Day',
    description: 'College graduation ceremony',
    category: 'Milestone',
    date: '2024-05-25',
    location: 'Boston, MA',
    story: 'Finally graduated! Four years of hard work paid off. So proud of this achievement.',
    notes: 'Frame the diploma',
    tags: ['graduation', 'milestone', 'achievement', 'education'],
    mood: 'Proud',
    source: 'Personal',
    highlights: 'Ceremony, cap toss, family celebration',
    image_url: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=800&h=600&fit=crop',
    likes: 120,
  },
  {
    title: 'Wedding Anniversary',
    description: '10th wedding anniversary celebration',
    category: 'Love',
    date: '2024-06-10',
    location: 'Paris, France',
    story: 'Celebrated our 10th anniversary in the city of love. Every moment was magical.',
    notes: 'Best trip ever',
    tags: ['anniversary', 'love', 'travel', 'romance'],
    mood: 'Romantic',
    source: 'Personal',
    highlights: 'Eiffel Tower visit, romantic dinner, city tour',
    image_url: 'https://images.unsplash.com/photo-1519741497674-611481863552?w=800&h=600&fit=crop',
    likes: 95,
  },
  {
    title: 'Mountain Sunset',
    description: 'Beautiful sunset from the mountain top',
    category: 'Nature',
    date: '2024-07-22',
    location: 'Aspen, CO',
    story: 'Watched the most beautiful sunset from the mountain peak. Nature never fails to amaze.',
    notes: 'Bring camera next time',
    tags: ['sunset', 'nature', 'mountains', 'photography'],
    mood: 'Peaceful',
    source: 'Personal',
    highlights: 'Sunset colors, mountain view, peaceful moment',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&h=600&fit=crop',
    likes: 78,
  },
  {
    title: 'City Lights',
    description: 'Night cityscape photography',
    category: 'Urban',
    date: '2024-08-05',
    location: 'San Francisco, CA',
    story: 'Captured the city lights at night. The urban landscape looks so different after dark.',
    notes: 'Try different angles',
    tags: ['city', 'night', 'photography', 'urban'],
    mood: 'Inspired',
    source: 'Personal',
    highlights: 'City lights, night photography, urban exploration',
    image_url: 'https://images.unsplash.com/photo-1469854523086-cc02fe5d8800?w=800&h=600&fit=crop',
    likes: 56,
  },
  {
    title: 'Beach Sunset',
    description: 'Evening at the beach',
    category: 'Travel',
    date: '2024-07-30',
    location: 'Malibu, CA',
    story: 'Perfect end to a perfect day. The colors in the sky were absolutely stunning.',
    notes: 'Come back here',
    tags: ['beach', 'sunset', 'california', 'relaxation'],
    mood: 'Relaxed',
    source: 'Personal',
    highlights: 'Sunset colors, beach walk, peaceful evening',
    image_url: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&h=600&fit=crop',
    likes: 103,
  },
]

export const sampleGroups = [
  {
    name: 'Squad Scrapbook',
    description: 'Our amazing journey together - capturing all the moments that matter',
    image_url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400&h=300&fit=crop',
    is_public: true,
    category: 'friends',
    members_count: 12,
    memories_count: 145,
  },
  {
    name: 'College Friends',
    description: 'Memories from our college days - the best years of our lives',
    image_url: 'https://images.unsplash.com/photo-1511895426328-dc8714191300?w=400&h=300&fit=crop',
    is_public: true,
    category: 'education',
    members_count: 8,
    memories_count: 89,
  },
  {
    name: 'Family Moments',
    description: 'Family gatherings and celebrations - preserving our family history',
    image_url: 'https://images.unsplash.com/photo-1511988617509-a57c8a288659?w=400&h=300&fit=crop',
    is_public: true,
    category: 'family',
    members_count: 15,
    memories_count: 234,
  },
  {
    name: 'Travel Buddies',
    description: 'Adventures around the world - exploring new places together',
    image_url: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    is_public: true,
    category: 'travel',
    members_count: 6,
    memories_count: 67,
  },
  {
    name: 'Childhood Friends',
    description: 'Growing up together - from kids to adults, still best friends',
    image_url: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400&h=300&fit=crop',
    is_public: true,
    category: 'friends',
    members_count: 5,
    memories_count: 123,
  },
]

export const sampleUsers = [
  {
    name: 'Emily Johnson',
    email: 'emily.johnson@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop',
  },
  {
    name: 'Michael Smith',
    email: 'michael.smith@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&h=150&fit=crop',
  },
  {
    name: 'Sarah Lee',
    email: 'sarah.lee@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=150&h=150&fit=crop',
  },
  {
    name: 'David Brown',
    email: 'david.brown@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&h=150&fit=crop',
  },
  {
    name: 'Alex Johnson',
    email: 'alex.johnson@example.com',
    avatar_url: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&h=150&fit=crop',
  },
]
